
openapi: "3.1.0"
info:
    version: 2024.01.04
    title: BringYour
    description: |
        BringYour Privacy Agent acts as an agent to exercise privacy
        rights granted by a service privacy policy to a consumer.
        
        This API is offered pending consent by the user to allow
        BringYour Privacy Agent to act on their behalf to delete their personal data.
        
        This includes:
        
        - IP and location data
        - Opt out of all data sharing and marketing
        - Exercises your privacy rights to know where your data has been shared

        Privacy Agent depends on your country and region of residence, email, 
        and username or email or phone number or account number of the service. 
        You authorize BringYour Privacy Advocate AI to send emails as your agent,
        and bcc all correspondence confidentially to your email.
        Privacy Agent will report any services that fail to comply to the 
        appropriate government authority for enforcement.
        
        If Privacy Agent cannot act as your agent due to location of residence, 
        it will return a ready to send email that you can send yourself.

        Unless otherwise specified, time/date strings will be formatted
        in the Go default `2006-01-02 15:04:05.999999999 -0700 MST`.

    termsOfService: https://bringyour.com/terms
    contact:
        name: BringYour
        email: support@bringyour.com
        url: https://bringyour.com
    x-logo:
        url: https://bringyour.com/res/images/bringyour-wordmark-260.svg
        altText: BringYour
    license:
        name: Mozilla Public License, v. 2.0
        url: https://mozilla.org/MPL/2.0/
servers:
    - url: https://gpt.bringyour.com

security:
  - BearerAuth: []

paths:
    /gpt/privacypolicy:
        post:
            description: |
                Returns a complete privacy policy text that best represents the official service URLs provided.
                This follows the privacy policy text guidelines at https://privacytxt.dev .
            operationId: GPT Privacy Policy
            security: []
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/GptPrivacyPolicyArgs"
            responses:
                "200":
                    description: |
                        A complete privacy policy text that best represents the official service URLs given.
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/GptPrivacyPolicyResult"

    /gpt/cookiedisclosure:
        post:
            description: |
                Returns a listing of actual cookies in the rendered page.
                It's in the site's interest to to support accurate cookie disclosure
                since this is used to generate a privacy.txt file as described at 
                https://privacytxt.dev . This disclosure may be used to enforce runtime behavior.
                This attempts to tap the "accept cookies" banner for a full cookie payload.
                Based on [privacy-txt-tools](https://github.com/privacy-txt/privacy-txt-tools)
            operationId: GPT Cookie Disclosure
            security: []
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/GptCookieDisclosureArgs"
            responses:
                "200":
                    description: |
                        A listing of actual cookies in the rendered page.
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/GptCookieDisclosureResult"
    /gpt/auditprivacytxt:
        post:
            description: |
                Audits the privacy.txt file for the given URL.
                The result includes the parsed format and errors.
                For suggestions, typically a UI will diff a generated format
                with the parsed format and suggest additions/changes.
            operationId: GPT Audit Privacy Txt
            security: []
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/GptAuditPrivacyTxtArgs"
            responses:
                "200":
                    description: |
                        The parsed format and errors.
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/GptAuditPrivacyTxtResult"

    /gpt/bemyprivacyagent:
        post:
            description: |
                Ask the Privacy Agent to act on the user's behalf to send
                the email provided, derived from the privacy policy,
                and handle all following correspondence.
                If the Privacy Agent cannot send the email, due to location of residence,
                then the user should send an email themselves.
            operationId: GPT Be My Privacy Agent
            security: []
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/GptBeMyPrivacyAgentArgs"
            responses:
                "200":
                    description: |
                        Whether the Privacy Agent can accept the consumer as their agent 
                        and run the process on their behalf. 
                        If true there is nothing else to do, 
                        the agent is already handling this request.
                        If false, the user should send an email on their own behalf.
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/GptBeMyPrivacyAgentResult"

components:
    securitySchemes:
        BearerAuth:
            type: http
            scheme: bearer
            description: BringYour JWT

    schemas:
        PrivacyTxtCookie:
            type: object
            description: |
                These fields follow the Cookie: formatted line from https://privacytxt.dev . 
            properties:
                name:
                    type: string
                domain_name:
                    type: string
                duration:
                    type: integer
                first_party:
                    type: boolean
                optional:
                    type: boolean
                http_only:
                    type: boolean
                secure_status:
                    type: boolean

        PrivacyTxtBanner:
            type: object
            description: |
                These fields follow the Banner: formatted line from https://privacytxt.dev . 
            properties:
                consent_present:
                    type: string
                consent_platform:
                    type: string

        PrivacyTxtAction:
            type: object
            description: |
                These fields follow the Action-*: formatted line from https://privacytxt.dev . 
            properties:
                name:
                    description: The action name as defined in the Action-* spec at https://privacytxt.dev 
                    type: string
                friendly_name:
                    description: |
                        The human friendly action name.
                        Dashes "-" are replaced with spaces " ".
                        The first word is capitalized.
                        e.g. "delete-personal-data" becomes "Delete personal data"
                    type: string
                value:
                    type: string

        GptPrivacyPolicyArgs:
            type: object
            required:
                - service_urls
            properties:
                service_name:
                    description: The name of the service
                    type: string
                service_urls:
                    description: |
                        Official URLs of the service to search for a complete privacy policy text
                    type: array
                    items:
                        type: string

        GptPrivacyPolicyResult:
            type: object
            properties:
                found:
                    description: |
                        Whether a complete privacy policy text was found for the URLs given
                    type: boolean
                privacy_policy_url:
                    description: the top level privacy policy URL as it exists in the URLs given
                    type: string
                privacy_policy:
                    description: a complete privacy policy text
                    type: string

        GptCookieDisclosureArgs:
            type: object
            required:
                - service_urls
            properties:
                service_name:
                    description: The name of the service
                    type: string
                service_urls:
                    description: |
                        Official URLs of the service to render.
                    type: array
                    items:
                        type: string

        GptCookieDisclosureResult:
            type: object
            properties:
                found:
                    description: |
                        Whether a complete cookie listing was found for the URLs given
                    type: boolean
                privacy_banner_accepted:
                    description: |
                        Whether a privacy banner was accepted on any of URLs given
                    type: boolean
                cookies:
                    description: a complete cookie listing
                    type: array
                    items:
                        $ref: "#/components/schemas/PrivacyTxtCookie"

        GptAuditPrivacyTxtArgs:
            type: object
            required:
                - service_url
            properties:
                service_name:
                    description: The name of the service
                    type: string
                service_url:
                    description: |
                        An official URL of the service.
                    type: string

        GptAuditPrivacyTxtResult:
            type: object
            properties:
                found:
                    description: |
                        Whether a privacy.txt was found for the URL given
                    type: boolean
                canonical_url:
                    description: |
                        The canonical url of the parsed privacy.txt file
                    type: string
                privacy_txt:
                    type: object
                    properties:
                        entity:
                            type: string
                        entity_country:
                            type: string
                        privacy_policy_text:
                            type: string
                        privacy_policy:
                            type: string
                        contact:
                            type: string
                        actions:
                            type: array
                            items:
                                $ref: "#/components/schemas/PrivacyTxtAction"
                        implied_actions:
                            description: |
                                The spec implies actions that are not explicitly stated.
                                This field enumerates the implied actions.
                            type: array
                            items:
                                $ref: "#/components/schemas/PrivacyTxtAction"
                        banner:
                            $ref: "#/components/schemas/PrivacyTxtBanner"
                        cookies:
                            type: array
                            items:
                                $ref: "#/components/schemas/PrivacyTxtCookie"
                errors:
                    description: |
                        Any error means the file failed audit.
                        The error message will explain the reason.
                    type: array
                    items:
                        type: string
                comments:
                    description: |
                        Suggestions and feedback on the audited file.
                        This is a grab bag of feedback items in no particular order.
                    type: array
                    items:
                        type: string

        GptBeMyPrivacyAgentArgs:
            type: object
            properties:
                country_of_residence:
                    description: Consumer's country of residence
                    type: string
                region_of_residence:
                    description: Consumer's region of residence, e.g. state or province
                    type: string
                correspondence_email:
                    description: |
                        Consumer's email that will be used by Privacy Agent 
                        to confidentially bcc correspondence and forward results
                    type: string
                consent:
                    description: |
                        Consent by the consumer to allow BringYour Privacy Agent 
                        to act on their behalf to delete their personal data.
                    type: boolean
                email_text:
                    description: |
                        A complete ready to send email that Privacy Agent 
                        will send to start the deletion process. The email text must contain:
                        - to email address for the service
                        - subject
                        - body text

                        The email should make it clear that BringYour 
                        has been authorized by the consumer to act on their behalf.
                        
                        The mailing address of BringYour is:

                        2261 Market Street #5245
                        San Francisco, CA 94114
                    type: object
                    properties:
                        to:
                            description: Email to the service privacy team from the policy
                            type: string
                        subject:
                            description: Email subject
                            type: string
                        body:
                            description: Email body text
                            type: string
                service_name:
                    description: The name of the service
                    type: string
                service_user:
                    description: |
                        The user name, email, phone number, or account number
                        used with the service
                    type: string

        GptBeMyPrivacyAgentResult:
            type: object
            properties:
                accepted:
                    description: |
                        Whether the Privacy Agent can accept the consumer as their agent 
                        and run the process on their behalf. 
                        If true there is nothing else to do, 
                        the agent is already handling this request.

                        If false, the user should send an email on their own behalf.
                        In this case the email should not mention that BringYour Privacy Agent 
                        is acting on their behalf.
                    type: boolean

