name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Current Repo
        uses: actions/checkout@v3
        with:
          path: bringyour

      - name: Checkout Another Repo
        uses: actions/checkout@v4

      - name: "Setup env"
        uses: JRMurr/direnv-nix-action@v4.1.0

      - name: Use Latest userwireguard and protocol
        run: |
          go mod edit -dropreplace github.com/urnetwork/userwireguard@v0.0.0
          go mod edit -dropreplace github.com/urnetwork/protocol@v0.0.0
          go mod edit -require github.com/urnetwork/userwireguard@latest -require github.com/urnetwork/protocol@latest
          go mod tidy

      - name: Run Tests
        run: |
          go test -v -test.short ./...
