name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Current Repo
        uses: actions/checkout@v3
        with:
          path: bringyour

      - name: Checkout Another Repo
        uses: actions/checkout@v3

      - uses: actions/setup-go@v5
        with:
          go-version: "^1.23.0"

      - name: Run Tests
        run: |
          go test ./...
